version: "3.3"
services:
  managebot:
    container_name: managebot
    privileged: true
    restart: unless-stopped
    image: "ghcr.io/xdFNLeaks/managebot:latest"
    volumes:
      - ./config:/usr/src/app/config
      - /var/run/docker.sock:/var/run/docker.sock
